### ISSUE TITLE
Chipreader has gone into "unkown" state in Home Assistant

### ISSUE THREAD

**Issue by hausner** [PTST/G4S-HomeAssistant#11]
After the last Home Assistant Release (i think) the G4S chipreader has gone into "unkown" state

I can still enable/disable the alarm via the actions in HA. Also the temperature measurement which is build-into the chipreader is still being read just fine. 

![image](https://github.com/user-attachments/assets/bd109f15-e49e-43a2-ad9c-0b05aea9a02a)

I see nothing in the log that seems related, only a warning about something that will be deprecated in 2025. 

2024-11-08 16:06:53.020 WARNING (ImportExecutor_0) [homeassistant.const] STATE_ALARM_ARMED_AWAY was used from g4s_alarm, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.ARMED_AWAY instead, please report it to the author of the 'g4s_alarm' custom integration
2024-11-08 16:06:53.029 WARNING (ImportExecutor_0) [homeassistant.const] STATE_ALARM_ARMED_NIGHT was used from g4s_alarm, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.ARMED_NIGHT instead, please report it to the author of the 'g4s_alarm' custom integration
2024-11-08 16:06:53.036 WARNING (ImportExecutor_0) [homeassistant.const] STATE_ALARM_DISARMED was used from g4s_alarm, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.DISARMED instead, please report it to the author of the 'g4s_alarm' custom integration
2024-11-08 16:06:53.043 WARNING (ImportExecutor_0) [homeassistant.const] STATE_ALARM_PENDING was used from g4s_alarm, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.PENDING instead, please report it to the author of the 'g4s_alarm' custom integration

2024-11-08 16:07:07.234 WARNING (MainThread) [homeassistant.components.alarm_control_panel] Entity None (<class 'custom_components.g4s_alarm.alarm_control_panel.G4sAlarm'>) is setting state directly which will stop working in HA Core 2025.11. Entities should implement the 'alarm_state' property and return its state using the AlarmControlPanelState enum, please report it to the custom integration author.

**Comment by PTST** [comment]
I can replicate the issue on the latest home assistant version, I will look into it when I have a moment

**Comment by hausner** [comment]
Sounds good
Let me know if i can help in any way.

Real happy about this integration :-)

**Comment by PTST** [comment]
I have released 0.3.0 which should fix this issue, please let me know if it works as expected 🙂

**Comment by hausner** [comment]
Didnt work here. I still get unknown state.
I downloaded the 0.3.0. release and unpacked in custom_components/g4s_alarm. Then reloaded the integration.

**Comment by PTST** [comment]
Did you do a complete reboot of HA?
Is their anything in the logs?

**Comment by hausner** [comment]
Found these
2024-11-11 08:34:32.253 INFO (SyncWorker_14) [homeassistant.util.package] Attempting install of G4S==1.0.10

and then later multiple times

2024-11-11 08:36:04.913 INFO (MainThread) [custom_components.g4s_alarm] Could not find user for last change


So no errors

**Comment by hausner** [comment]
did a reboot after reloading the integration alone did not work.
And also updated to latest "hotfix" from HA.

**Comment by hausner** [comment]
the _pychache_ folder still has old files.
Should i flush that folder?
![image](https://github.com/user-attachments/assets/691fb5dc-96e0-49c3-87b2-5351ce95c222)

**Comment by PTST** [comment]
Can't hurt to delete them and restart.

Any particular reason you don't install via HACS?

**Comment by hausner** [comment]
It did not have a reference to v. 0.3.0 only  0.2.8 in HACS

![image](https://github.com/user-attachments/assets/0b8f662b-b1c1-4810-9d70-5a64066ef73a)

**Comment by PTST** [comment]
If you click on the 3 dots in the top right corner and then update information it will pull the latest info and releases from GitHub 

![image](https://github.com/user-attachments/assets/5694d1f7-2e23-420b-b40d-ed591c5aca35)

**Comment by hausner** [comment]
Just did that and now it works.
So something was not updated in the manual way.

thanks for the quick fix :-)

**Comment by PTST** [comment]
Great 👍
